// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoClient {
    
    
    public partial class Preferences {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Frame LoginFrame;
        
        private Gtk.Alignment GtkAlignment14;
        
        private Gtk.Table table1;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Button LoginButton;
        
        private Gtk.Entry PasswordEntry;
        
        private Gtk.Entry UserNameEntry;
        
        private Gtk.VBox vbox5;
        
        private Gtk.CheckButton SaveLogincheckbutton;
        
        private Gtk.Label GtkLabel24;
        
        private Gtk.Label label6;
        
        private Gtk.Label label3;
        
        private Gtk.FileChooserWidget MusicPathChooser;
        
        private Gtk.Label label1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment GtkAlignment12;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton TopTrackscheckbutton;
        
        private Gtk.CheckButton Lovedcheckbutton;
        
        private Gtk.CheckButton Weekcheckbutton;
        
        private Gtk.CheckButton TopTracksMixcheckbutton;
        
        private Gtk.CheckButton LovedMixcheckbutton;
        
        private Gtk.CheckButton WeekMixcheckbutton;
        
        private Gtk.CheckButton AllMixcheckbutton;
        
        private Gtk.Label GtkLabel20;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment13;
        
        private Gtk.VBox vbox2;
        
        private Gtk.CheckButton M3Ucheckbutton;
        
        private Gtk.CheckButton PLScheckbutton;
        
        private Gtk.CheckButton SMILcheckbutton;
        
        private Gtk.Label GtkLabel23;
        
        private Gtk.Label label2;
        
        private Gtk.Button Closebutton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoClient.Preferences
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "MonoClient.Preferences";
            this.Title = Mono.Unix.Catalog.GetString("Preferences");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.HasSeparator = false;
            // Internal child MonoClient.Preferences.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            // Container child vbox4.Gtk.Box+BoxChild
            this.LoginFrame = new Gtk.Frame();
            this.LoginFrame.Sensitive = false;
            this.LoginFrame.Name = "LoginFrame";
            this.LoginFrame.ShadowType = ((Gtk.ShadowType)(0));
            this.LoginFrame.LabelXalign = 0F;
            // Container child LoginFrame.Gtk.Container+ContainerChild
            this.GtkAlignment14 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment14.Name = "GtkAlignment14";
            this.GtkAlignment14.LeftPadding = ((uint)(12));
            // Container child GtkAlignment14.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = "Password: ";
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = "Username: ";
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.LoginButton = new Gtk.Button();
            this.LoginButton.CanFocus = true;
            this.LoginButton.Name = "LoginButton";
            // Container child LoginButton.Gtk.Container+ContainerChild
            Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w4.Name = "GtkAlignment";
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w5 = new Gtk.HBox();
            w5.Name = "GtkHBox";
            w5.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w6 = new Gtk.Image();
            w6.Name = "image6";
            w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w5.Add(w6);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w8 = new Gtk.Label();
            w8.Name = "GtkLabel1";
            w8.LabelProp = Mono.Unix.Catalog.GetString("Login");
            w5.Add(w8);
            w4.Add(w5);
            this.LoginButton.Add(w4);
            this.table1.Add(this.LoginButton);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.LoginButton]));
            w12.TopAttach = ((uint)(2));
            w12.BottomAttach = ((uint)(3));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.PasswordEntry = new Gtk.Entry();
            this.PasswordEntry.CanFocus = true;
            this.PasswordEntry.Name = "PasswordEntry";
            this.PasswordEntry.IsEditable = true;
            this.PasswordEntry.Visibility = false;
            this.PasswordEntry.InvisibleChar = '●';
            this.table1.Add(this.PasswordEntry);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.PasswordEntry]));
            w13.TopAttach = ((uint)(1));
            w13.BottomAttach = ((uint)(2));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.UserNameEntry = new Gtk.Entry();
            this.UserNameEntry.CanFocus = true;
            this.UserNameEntry.Name = "UserNameEntry";
            this.UserNameEntry.IsEditable = true;
            this.UserNameEntry.InvisibleChar = '●';
            this.table1.Add(this.UserNameEntry);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.UserNameEntry]));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            // Container child vbox5.Gtk.Box+BoxChild
            this.SaveLogincheckbutton = new Gtk.CheckButton();
            this.SaveLogincheckbutton.CanFocus = true;
            this.SaveLogincheckbutton.Name = "SaveLogincheckbutton";
            this.SaveLogincheckbutton.Label = "Remember password";
            this.SaveLogincheckbutton.DrawIndicator = true;
            this.vbox5.Add(this.SaveLogincheckbutton);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox5[this.SaveLogincheckbutton]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            this.table1.Add(this.vbox5);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.vbox5]));
            w16.TopAttach = ((uint)(2));
            w16.BottomAttach = ((uint)(3));
            w16.LeftAttach = ((uint)(1));
            w16.RightAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment14.Add(this.table1);
            this.LoginFrame.Add(this.GtkAlignment14);
            this.GtkLabel24 = new Gtk.Label();
            this.GtkLabel24.Name = "GtkLabel24";
            this.GtkLabel24.LabelProp = Mono.Unix.Catalog.GetString("<b>Login</b>");
            this.GtkLabel24.UseMarkup = true;
            this.LoginFrame.LabelWidget = this.GtkLabel24;
            this.vbox4.Add(this.LoginFrame);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox4[this.LoginFrame]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = "Please login and set the Music directory before you preceed.";
            this.label6.Wrap = true;
            this.vbox4.Add(this.label6);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox4[this.label6]));
            w20.Position = 1;
            w20.Expand = false;
            this.notebook1.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w21 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
            w21.TabExpand = false;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = "User preferences";
            this.notebook1.SetTabLabel(this.vbox4, this.label3);
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.MusicPathChooser = new Gtk.FileChooserWidget(((Gtk.FileChooserAction)(2)));
            this.MusicPathChooser.Name = "MusicPathChooser";
            this.notebook1.Add(this.MusicPathChooser);
            Gtk.Notebook.NotebookChild w22 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.MusicPathChooser]));
            w22.Position = 1;
            w22.TabExpand = false;
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = "Music directory";
            this.notebook1.SetTabLabel(this.MusicPathChooser, this.label1);
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(0));
            this.frame5.LabelXalign = 0F;
            // Container child frame5.Gtk.Container+ContainerChild
            this.GtkAlignment12 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment12.Name = "GtkAlignment12";
            this.GtkAlignment12.LeftPadding = ((uint)(12));
            // Container child GtkAlignment12.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            // Container child vbox3.Gtk.Box+BoxChild
            this.TopTrackscheckbutton = new Gtk.CheckButton();
            this.TopTrackscheckbutton.CanFocus = true;
            this.TopTrackscheckbutton.Name = "TopTrackscheckbutton";
            this.TopTrackscheckbutton.Label = "Top tracks";
            this.TopTrackscheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.TopTrackscheckbutton);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox3[this.TopTrackscheckbutton]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.Lovedcheckbutton = new Gtk.CheckButton();
            this.Lovedcheckbutton.CanFocus = true;
            this.Lovedcheckbutton.Name = "Lovedcheckbutton";
            this.Lovedcheckbutton.Label = "Recent loved tracks";
            this.Lovedcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.Lovedcheckbutton);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.Lovedcheckbutton]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.Weekcheckbutton = new Gtk.CheckButton();
            this.Weekcheckbutton.CanFocus = true;
            this.Weekcheckbutton.Name = "Weekcheckbutton";
            this.Weekcheckbutton.Label = "Weekly track chart";
            this.Weekcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.Weekcheckbutton);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.Weekcheckbutton]));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.TopTracksMixcheckbutton = new Gtk.CheckButton();
            this.TopTracksMixcheckbutton.CanFocus = true;
            this.TopTracksMixcheckbutton.Name = "TopTracksMixcheckbutton";
            this.TopTracksMixcheckbutton.Label = "Top tracks mixed";
            this.TopTracksMixcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.TopTracksMixcheckbutton);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox3[this.TopTracksMixcheckbutton]));
            w26.Position = 3;
            w26.Expand = false;
            w26.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.LovedMixcheckbutton = new Gtk.CheckButton();
            this.LovedMixcheckbutton.CanFocus = true;
            this.LovedMixcheckbutton.Name = "LovedMixcheckbutton";
            this.LovedMixcheckbutton.Label = "Recent loved tracks mixed";
            this.LovedMixcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.LovedMixcheckbutton);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox3[this.LovedMixcheckbutton]));
            w27.Position = 4;
            w27.Expand = false;
            w27.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.WeekMixcheckbutton = new Gtk.CheckButton();
            this.WeekMixcheckbutton.CanFocus = true;
            this.WeekMixcheckbutton.Name = "WeekMixcheckbutton";
            this.WeekMixcheckbutton.Label = "Weekly track chart mixed";
            this.WeekMixcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.WeekMixcheckbutton);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox3[this.WeekMixcheckbutton]));
            w28.Position = 5;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.AllMixcheckbutton = new Gtk.CheckButton();
            this.AllMixcheckbutton.CanFocus = true;
            this.AllMixcheckbutton.Name = "AllMixcheckbutton";
            this.AllMixcheckbutton.Label = "All tracks mixed";
            this.AllMixcheckbutton.DrawIndicator = true;
            this.vbox3.Add(this.AllMixcheckbutton);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox3[this.AllMixcheckbutton]));
            w29.Position = 6;
            w29.Expand = false;
            w29.Fill = false;
            this.GtkAlignment12.Add(this.vbox3);
            this.frame5.Add(this.GtkAlignment12);
            this.GtkLabel20 = new Gtk.Label();
            this.GtkLabel20.Name = "GtkLabel20";
            this.GtkLabel20.LabelProp = Mono.Unix.Catalog.GetString("<b>Playlists</b>");
            this.GtkLabel20.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel20;
            this.hbox1.Add(this.frame5);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame5]));
            w32.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            this.frame4.LabelXalign = 0F;
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment13 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment13.Name = "GtkAlignment13";
            this.GtkAlignment13.LeftPadding = ((uint)(12));
            // Container child GtkAlignment13.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            // Container child vbox2.Gtk.Box+BoxChild
            this.M3Ucheckbutton = new Gtk.CheckButton();
            this.M3Ucheckbutton.CanFocus = true;
            this.M3Ucheckbutton.Name = "M3Ucheckbutton";
            this.M3Ucheckbutton.Label = ".m3u";
            this.M3Ucheckbutton.DrawIndicator = true;
            this.vbox2.Add(this.M3Ucheckbutton);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox2[this.M3Ucheckbutton]));
            w33.Position = 0;
            w33.Expand = false;
            w33.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.PLScheckbutton = new Gtk.CheckButton();
            this.PLScheckbutton.CanFocus = true;
            this.PLScheckbutton.Name = "PLScheckbutton";
            this.PLScheckbutton.Label = ".pls";
            this.PLScheckbutton.DrawIndicator = true;
            this.vbox2.Add(this.PLScheckbutton);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox2[this.PLScheckbutton]));
            w34.Position = 1;
            w34.Expand = false;
            w34.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.SMILcheckbutton = new Gtk.CheckButton();
            this.SMILcheckbutton.CanFocus = true;
            this.SMILcheckbutton.Name = "SMILcheckbutton";
            this.SMILcheckbutton.Label = ".smil";
            this.SMILcheckbutton.DrawIndicator = true;
            this.vbox2.Add(this.SMILcheckbutton);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox2[this.SMILcheckbutton]));
            w35.Position = 2;
            w35.Expand = false;
            w35.Fill = false;
            this.GtkAlignment13.Add(this.vbox2);
            this.frame4.Add(this.GtkAlignment13);
            this.GtkLabel23 = new Gtk.Label();
            this.GtkLabel23.Name = "GtkLabel23";
            this.GtkLabel23.LabelProp = Mono.Unix.Catalog.GetString("<b>Output formats</b>");
            this.GtkLabel23.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel23;
            this.hbox1.Add(this.frame4);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame4]));
            w38.Position = 1;
            w38.Expand = false;
            w38.Fill = false;
            this.notebook1.Add(this.hbox1);
            Gtk.Notebook.NotebookChild w39 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox1]));
            w39.Position = 2;
            w39.TabExpand = false;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = "Playlist settings";
            this.notebook1.SetTabLabel(this.hbox1, this.label2);
            w1.Add(this.notebook1);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(w1[this.notebook1]));
            w40.Position = 0;
            // Internal child MonoClient.Preferences.ActionArea
            Gtk.HButtonBox w41 = this.ActionArea;
            w41.Events = ((Gdk.EventMask)(256));
            w41.Name = "MonoClient.Preferences_ActionArea";
            w41.Spacing = 6;
            w41.BorderWidth = ((uint)(5));
            w41.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child MonoClient.Preferences_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.Closebutton = new Gtk.Button();
            this.Closebutton.CanDefault = true;
            this.Closebutton.CanFocus = true;
            this.Closebutton.Name = "Closebutton";
            // Container child Closebutton.Gtk.Container+ContainerChild
            Gtk.Alignment w42 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w42.Name = "GtkAlignment8";
            // Container child GtkAlignment8.Gtk.Container+ContainerChild
            Gtk.HBox w43 = new Gtk.HBox();
            w43.Name = "GtkHBox13";
            w43.Spacing = 2;
            // Container child GtkHBox13.Gtk.Container+ContainerChild
            Gtk.Image w44 = new Gtk.Image();
            w44.Name = "image7";
            w44.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-close", Gtk.IconSize.Menu, 16);
            w43.Add(w44);
            // Container child GtkHBox13.Gtk.Container+ContainerChild
            Gtk.Label w46 = new Gtk.Label();
            w46.Name = "GtkLabel19";
            w46.LabelProp = Mono.Unix.Catalog.GetString("Close");
            w43.Add(w46);
            w42.Add(w43);
            this.Closebutton.Add(w42);
            this.AddActionWidget(this.Closebutton, 0);
            Gtk.ButtonBox.ButtonBoxChild w50 = ((Gtk.ButtonBox.ButtonBoxChild)(w41[this.Closebutton]));
            w50.Expand = false;
            w50.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 286;
            this.Show();
            this.UserNameEntry.Changed += new System.EventHandler(this.OnUserNameEntryChanged);
            this.LoginButton.Clicked += new System.EventHandler(this.OnLoginButtonClicked);
        }
    }
}
