.TH THELASTRIPPER 1 "March  10, 2007"
.SH NAME TheLastRipper \- An audio stream ripper for Last.fm.
.SH DESCRIPTION
TheLastRipper can save Last.fm streams to mp3's, while downloading 
album cover, appending ID3v1 tags and organizing you music after 
Artist/Album/Track. TheLastRipper will also help you generate playlists 
from the data available from you Last.fm account. 
TheLastRipper requires a Last.fm login, you can regsiter for free 
at http://last.fm/
Please note that recordings of radio streams, may NOT be legal, 
we recommend that you investegate you local laws, before using 
TheLastRipper.
.SH AUTHOR
thelastripper was written by TheLastRipper developer team.
.PP
This manual page was written by Jop... (Jonas F. Jensen). <Jopsen@gmail.com>,
for the Debian project (but may be used by others).
.SH COPYRIGHT TheLastRipper is Copyright (c) 2007 Jop... (Jonas F. Jensen).
This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation; either version 2 of the License, 
or (at your option) any later version.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
MA 02111-1307 USA.
