// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoClient {
    
    
    public partial class CreateLockerAccount {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label label5;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Table table3;
        
        private Gtk.Entry FirstNameEntry;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Entry LastnameEntry;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.Table table4;
        
        private Gtk.Label label10;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Entry MailEntry;
        
        private Gtk.Entry Pwd2Entry;
        
        private Gtk.Entry PwdEntry;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoClient.CreateLockerAccount
            this.Name = "MonoClient.CreateLockerAccount";
            this.Title = Mono.Unix.Catalog.GetString("Create new MP3tunes account");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.HasSeparator = false;
            // Internal child MonoClient.CreateLockerAccount.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.WidthRequest = 400;
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("This dialog will help you create an MP3Tunes account to where you can upload all your music. See MP3tunes.com for more information...");
            this.label5.Wrap = true;
            this.vbox3.Add(this.label5);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.label5]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.FirstNameEntry = new Gtk.Entry();
            this.FirstNameEntry.CanFocus = true;
            this.FirstNameEntry.Name = "FirstNameEntry";
            this.FirstNameEntry.IsEditable = true;
            this.FirstNameEntry.InvisibleChar = '●';
            this.table3.Add(this.FirstNameEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table3[this.FirstNameEntry]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("First name");
            this.table3.Add(this.label6);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table3[this.label6]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Last name");
            this.table3.Add(this.label7);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table3[this.label7]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.LastnameEntry = new Gtk.Entry();
            this.LastnameEntry.CanFocus = true;
            this.LastnameEntry.Name = "LastnameEntry";
            this.LastnameEntry.IsEditable = true;
            this.LastnameEntry.InvisibleChar = '●';
            this.table3.Add(this.LastnameEntry);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table3[this.LastnameEntry]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment2.Add(this.table3);
            this.frame2.Add(this.GtkAlignment2);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>Name</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel2;
            this.vbox3.Add(this.frame2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame2]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.table4 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 0F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Password again");
            this.table4.Add(this.label10);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table4[this.label10]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("E-mail");
            this.table4.Add(this.label8);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table4[this.label8]));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 0F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.table4.Add(this.label9);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table4[this.label9]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.MailEntry = new Gtk.Entry();
            this.MailEntry.CanFocus = true;
            this.MailEntry.Name = "MailEntry";
            this.MailEntry.IsEditable = true;
            this.MailEntry.InvisibleChar = '●';
            this.table4.Add(this.MailEntry);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table4[this.MailEntry]));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.Pwd2Entry = new Gtk.Entry();
            this.Pwd2Entry.CanFocus = true;
            this.Pwd2Entry.Name = "Pwd2Entry";
            this.Pwd2Entry.IsEditable = true;
            this.Pwd2Entry.Visibility = false;
            this.Pwd2Entry.InvisibleChar = '●';
            this.table4.Add(this.Pwd2Entry);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table4[this.Pwd2Entry]));
            w14.TopAttach = ((uint)(2));
            w14.BottomAttach = ((uint)(3));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.PwdEntry = new Gtk.Entry();
            this.PwdEntry.CanFocus = true;
            this.PwdEntry.Name = "PwdEntry";
            this.PwdEntry.IsEditable = true;
            this.PwdEntry.Visibility = false;
            this.PwdEntry.InvisibleChar = '●';
            this.table4.Add(this.PwdEntry);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table4[this.PwdEntry]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment3.Add(this.table4);
            this.frame3.Add(this.GtkAlignment3);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Login credentials</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel3;
            this.vbox3.Add(this.frame3);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame3]));
            w18.Position = 2;
            w18.Expand = false;
            w18.Fill = false;
            w1.Add(this.vbox3);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(w1[this.vbox3]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Internal child MonoClient.CreateLockerAccount.ActionArea
            Gtk.HButtonBox w20 = this.ActionArea;
            w20.Name = "dialog1_ActionArea";
            w20.Spacing = 6;
            w20.BorderWidth = ((uint)(5));
            w20.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w21 = ((Gtk.ButtonBox.ButtonBoxChild)(w20[this.buttonCancel]));
            w21.Expand = false;
            w21.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseUnderline = true;
            // Container child buttonOk.Gtk.Container+ContainerChild
            Gtk.Alignment w22 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w23 = new Gtk.HBox();
            w23.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w24 = new Gtk.Image();
            w24.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-connect", Gtk.IconSize.Menu, 16);
            w23.Add(w24);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w26 = new Gtk.Label();
            w26.LabelProp = Mono.Unix.Catalog.GetString("Create _new Locker");
            w26.UseUnderline = true;
            w23.Add(w26);
            w22.Add(w23);
            this.buttonOk.Add(w22);
            w20.Add(this.buttonOk);
            Gtk.ButtonBox.ButtonBoxChild w30 = ((Gtk.ButtonBox.ButtonBoxChild)(w20[this.buttonOk]));
            w30.Position = 1;
            w30.Expand = false;
            w30.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 414;
            this.DefaultHeight = 307;
            this.Show();
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        }
    }
}
